// Fill out your copyright notice in the Description page of Project Settings.


#include "SExplosiveBarrel.h"

#include "PhysicsEngine/RadialForceComponent.h"

// Sets default values
ASExplosiveBarrel::ASExplosiveBarrel()
{
	// It is generated by the code template.
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	// PrimaryActorTick.bCanEverTick = true;
	this->MeshComp = CreateDefaultSubobject<UStaticMeshComponent>("MeshComp");
		this->MeshComp->SetSimulatePhysics(true);
	// The change of profile will be done automatically in Blueprint, while it must be done manually in C++.
	this->MeshComp->SetCollisionProfileName(UCollisionProfile::PhysicsActor_ProfileName);
	RootComponent = MeshComp;

	this->ForceComp = CreateDefaultSubobject<URadialForceComponent>("ForceComp");
	this->ForceComp->SetupAttachment(MeshComp);
	// If it is true, it will constantly impose impulse in every tick.
	// We replace it with FireImpulse() which is triggered by event.
	this->ForceComp->SetAutoActivate(false);
	this->ForceComp->Radius = 750.0f;
	this->ForceComp->ImpulseStrength = 2500.0f;
	// If true, the impulse will ignore mass of objects and will always result in a fixed velocity change.
	this->ForceComp->bImpulseVelChange = true;
	// By default, Pawn, PhysicsBody, Vehicle and Destructible are added.
	this->ForceComp->AddCollisionChannelToAffect(ECC_WorldDynamic);
}

// Called when the game starts or when spawned
void ASExplosiveBarrel::BeginPlay()
{
	Super::BeginPlay();
	
}

// Allow actors to initialize themselves on the C++ side after all of their components have been initialized,
// only called during gameplay.
void ASExplosiveBarrel::PostInitializeComponents() {
	Super::PostInitializeComponents();
	// OnComponentHit will be triggered when the component hits or is hit.
	// AddDynamic is a kind of delegates.
	this->MeshComp->OnComponentHit.AddDynamic(this, &ASExplosiveBarrel::OnActorHit);
}

// Called every frame
void ASExplosiveBarrel::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

}

void ASExplosiveBarrel::OnActorHit(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp,
	FVector NormalImpulse, const FHitResult& Hit) {
	// It will fire a single impulse.
	ForceComp->FireImpulse();

	// It will have some log functions.
	UE_LOG(LogTemp, Log, TEXT("OnActorHit in Explosive Barrel"));
	UE_LOG(LogTemp, Warning, TEXT("OtherActor: %s, at game time %f"),
		*GetNameSafe(OtherActor), GetWorld()->TimeSeconds);
	FString CombinedString = FString::Printf(TEXT("Hit at location: %s"), *Hit.ImpactPoint.ToString());
	DrawDebugString(GetWorld(), Hit.ImpactPoint, CombinedString, nullptr, FColor::Green, 2.0f, true);
}
